# Generated by Django 3.0.7 on 2020-08-14 22:02

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import json_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='base_user',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'doctor'), (3, 'clerk')], default=1)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='clerk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('natural_code', models.IntegerField(null=True)),
                ('phone', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=40, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementApp.base_user')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('natural_code', models.IntegerField()),
                ('request_kind', models.CharField(max_length=255)),
                ('request_txt', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('natural_code', models.IntegerField(null=True)),
                ('msn', models.IntegerField(null=True)),
                ('phone', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=40, null=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('data', json_field.fields.JSONField(default='null', help_text='Enter a valid JSON object')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementApp.base_user')),
            ],
        ),
        migrations.CreateModel(
            name='reserve',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('reserve_time', models.DateTimeField()),
                ('natural_code', models.IntegerField()),
                ('clerk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementApp.clerk')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementApp.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='relation_doctor_hospital',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementApp.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='relation_doctor_clerk',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('clerk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementApp.clerk')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementApp.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='manager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('natural_code', models.IntegerField(null=True)),
                ('phone', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=40, null=True)),
                ('hospital_name', models.CharField(max_length=255)),
                ('hospital_id', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementApp.base_user')),
            ],
        ),
        migrations.CreateModel(
            name='free_time',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('free_time', models.DateTimeField()),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementApp.doctor')),
            ],
        ),
    ]
