# Generated by Django 3.0.7 on 2020-08-14 22:08

from django.db import migrations
import json_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='data',
            field=json_field.fields.JSONField(default='null', help_text='Enter a valid JSON object', null=True),
        ),
    ]
