# Generated by Django 3.0.7 on 2020-08-01 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='manager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('natural_code', models.IntegerField(null=True)),
                ('phone', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=40, null=True)),
                ('hospital_name', models.CharField(max_length=255)),
                ('hospital_id', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementApp.base_user')),
            ],
        ),
        migrations.RemoveField(
            model_name='clerk',
            name='hospital_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='hospital_id',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='hospital_id',
        ),
        migrations.RemoveField(
            model_name='free_time',
            name='hospital_id',
        ),
        migrations.RemoveField(
            model_name='relation_doctor_clerk',
            name='hospital_id',
        ),
        migrations.RemoveField(
            model_name='relation_doctor_hospital',
            name='hospital_id',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='hospital_id',
        ),
        migrations.DeleteModel(
            name='hospital',
        ),
    ]
