# Generated by Django 3.0.7 on 2020-06-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementApp', '0003_auto_20200621_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
