# Generated by Django 3.0.7 on 2020-06-21 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='hospital_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementApp.hospital'),
        ),
    ]
